# render.yaml (Modified for services within 'backend' folder)
services:
  # --- User Service ---
  - name: user-service         # Render service name (used for internal DNS)
    type: web                # Service type (web for HTTP services)
    env: docker              # Use Docker runtime
    plan: free               # Use the free instance type
    repo: https://github.com/amitpanwar789/G-Shop # Replace with your repo URL
    autoDeploy: true         # Automatically deploy on push to the main branch
    # --- Paths updated below ---
    dockerContext: ./backend/user-service # Path to the directory containing the Dockerfile relative to repo root
    dockerfilePath: ./backend/user-service/Dockerfile # Explicit path to Dockerfile relative to repo root
    envVars:
      - key: PORT
        value: 5000 # The port your app listens on internally
      - key: MONGO_URI
        fromSecret: MONGO_ATLAS_URI # Reference a secret (created in Render Env Groups)
      - key: JWT_SECRET
        fromSecret: SHARED_JWT_SECRET # Reference a secret
      - key: NODE_ENV
        value: production

  # --- Product Service ---
  - name: product-service
    type: web
    env: docker
    plan: free
    repo: https://github.com/amitpanwar789/G-Shop
    autoDeploy: true
    # --- Paths updated below ---
    dockerContext: ./backend/product-service
    dockerfilePath: ./backend/product-service/Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        fromSecret: MONGO_ATLAS_URI
      - key: JWT_SECRET
        fromSecret: SHARED_JWT_SECRET
      - key: NODE_ENV
        value: production

  # --- Order Service ---
  - name: order-service
    type: web
    env: docker
    plan: free
    repo: https://github.com/amitpanwar789/G-Shop
    autoDeploy: true
    # --- Paths updated below ---
    dockerContext: ./backend/order-service
    dockerfilePath: ./backend/order-service/Dockerfile
    envVars:
      - key: PORT
        value: 5003
      - key: MONGO_URI
        fromSecret: MONGO_ATLAS_URI
      - key: JWT_SECRET
        fromSecret: SHARED_JWT_SECRET
      - key: NODE_ENV
        value: production

  # --- Nginx Reverse Proxy ---
  - name: nginx # This will be your public-facing service (or handle API routing)
    type: web
    env: docker
    plan: free
    repo: https://github.com/amitpanwar789/G-Shop
    autoDeploy: true
    # --- Paths updated below ---
    dockerContext: ./backend/nginx
    dockerfilePath: ./backend/nginx/Dockerfile
    # IMPORTANT: Ensure your nginx.conf inside ./backend/nginx/
    # correctly proxies to the internal Render service names:
    # e.g., proxy_pass http://user-service:5000;

# Reminder: Define your secrets (MONGO_ATLAS_URI, SHARED_JWT_SECRET) in Render Dashboard
# under Environment Groups and ensure they are linked or added to each service.