# render.yaml (Corrected envVars syntax using fromGroup)
services:
  # --- User Service ---
  - name: user-service
    type: web
    env: docker
    plan: free
    repo: https://github.com/amitpanwar789/G-Shop # Replace with your repo URL
    autoDeploy: true
    dockerContext: ./backend/user-service
    dockerfilePath: ./backend/user-service/Dockerfile
    envVars:
      - key: PORT         # Regular key/value env var
        value: 5000
      - key: MONGO_URI    # Env var name available *in* your service
        fromGroup: microservice-secrets # Name of the Env Group created in Render
        secretKey: MONGO_ATLAS_URI      # Name of the secret *within* the Env Group
      - key: JWT_SECRET   # Env var name available *in* your service
        fromGroup: microservice-secrets # Name of the Env Group created in Render
        secretKey: SHARED_JWT_SECRET    # Name of the secret *within* the Env Group
      - key: NODE_ENV     # Regular key/value env var
        value: production

  # --- Product Service ---
  - name: product-service
    type: web
    env: docker
    plan: free
    repo: https://github.com/amitpanwar789/G-Shop
    autoDeploy: true
    dockerContext: ./backend/product-service
    dockerfilePath: ./backend/product-service/Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        fromGroup: microservice-secrets
        secretKey: MONGO_ATLAS_URI
      - key: JWT_SECRET
        fromGroup: microservice-secrets
        secretKey: SHARED_JWT_SECRET
      - key: NODE_ENV
        value: production

  # --- Order Service ---
  - name: order-service
    type: web
    env: docker
    plan: free
    repo: https://github.com/amitpanwar789/G-Shop
    autoDeploy: true
    dockerContext: ./backend/order-service
    dockerfilePath: ./backend/order-service/Dockerfile
    envVars:
      - key: PORT
        value: 5003
      - key: MONGO_URI
        fromGroup: microservice-secrets
        secretKey: MONGO_ATLAS_URI
      - key: JWT_SECRET
        fromGroup: microservice-secrets
        secretKey: SHARED_JWT_SECRET
      - key: NODE_ENV
        value: production

  # --- Nginx Reverse Proxy ---
  - name: nginx
    type: web
    env: docker
    plan: free
    repo: https://github.com/amitpanwar789/G-Shop
    autoDeploy: true
    dockerContext: ./backend/nginx
    dockerfilePath: ./backend/nginx/Dockerfile
    # No secrets needed for nginx in this example

  # --- Optional: Frontend Static Site ---
  # (Include this section if deploying frontend as a static site)
  # - name: frontend
  #   type: static
  #   repo: https://github.com/amitpanwar789/G-Shop
  #   autoDeploy: true
  #   rootDir: ./frontend
  #   buildCommand: npm install && npm run build # Adjust as needed
  #   publishDir: ./frontend/build             # Adjust as needed
  #   routes:
  #     - type: rewrite
  #       source: /*
  #       destination: /index.html