spring.application.name=user-service
server.port=5000

spring.data.mongodb.uri=mongodb://localhost:27018/users-service

# JWT Configuration
jwt.secret=SUP3RS3CR3TK3Y
jwt.expiration=86400000

logging.level.org.springframework.web=INFO
logging.level.com.gshop=DEBUG
